# Generated by Django 4.1 on 2022-10-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=1000)),
                ('show', models.BooleanField(default=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
