# Generated by Django 4.1 on 2022-10-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_category_book_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(null=True, upload_to='book_cover/'),
        ),
    ]
