# Generated by Django 4.1 on 2022-10-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('subject', models.CharField(max_length=120, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
